apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app: {{ .Values.appName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # AWS IAM Role association for EKS IRSA (IAM Roles for Service Accounts)
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.iamRoleArn }}